name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get autoconf
      run: sudo apt-get install autoconf
    - name: autoconfigure
      run: ./autogen.sh
    - name: configure
      run: LDFLAGS=-static ./configure
    - name: make
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v4.6.1
      with:
           name: output
           path: nasm
    - name: Upload freeldr.sys to GitHub Releases
      uses: softprops/action-gh-release@v1
      with: 
        path: "nasm"  # This grabs the output
        tag_name: latest
        token: ${{ secrets.GITHUB_TOKEN }}
