name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get autoconf
      run: sudo apt-get install autoconf
    - name: autoconfigure
      run: ./autogen.sh
    - name: configure
      run: LDFLAGS=-static ./configure
    - name: make
      run: make
